# Configuraci칩n de la base de datos
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/airbnb   # URL de conexi칩n a la base de datos PostgreSQL en el puerto 5432
    username: postgres                            # Nombre de usuario para conectar a la base de datos
    password: postgres                            # Contrase침a para conectar a la base de datos

  # Configuraci칩n de Liquibase
  liquibase:
    contexts: dev                                # Define el contexto de Liquibase para aplicar cambios, en este caso, 'dev' para desarrollo
